image: node:latest

cache:
  paths:
    - node_modules/

services:
  - mongo:latest

variables:
  MONGO_URI: 'mongo'
  NODE_ENV: 'test'


install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_with_lab:
  stage: test
  script: npm run test_gitlab
