# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9.2.0
definitions:
  services:
    mongo:
      image: mongo
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update # required to install zip
          - apt-get install -y python3 # required for packaging up the application
          - apt-get install wget 
          - wget https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - apt-get install -y zip # required for packaging up the application
          - pip install boto3==1.3.0 # required for codedeploy_deploy.py
          - git submodule update --init --recursive
          - npm install && cd ./react && npm install && cd ..  
          - npm test
          - npm build
          - npm build_client
          - zip -r /tmp/artifact.zip * # package up the application for deployment
          - python codedeploy_deploy.py # run the deployment script

        services: 
          - mongo 
